services:
  gadm-downloader:
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
      - ./gadm_downloader:/app/gadm_downloader

    command: ["python", "/app/gadm_downloader/main.py", "--file-mode", "read", "--db-mode", "check-if-exists"]
    # command: ["python", "/app/gadm_downloader/main.py", "--help"]

    environment:
      - LOG_LEVEL=DEBUG
