version: "3.9"

services:
  gadm-downloader:
    build: .
    image: gadm-downloader:latest
    container_name: gadm-downloader

    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
      - ./gadm_downloader:/app/gadm_downloader

    command: ["python", "gadm_downloader/main.py"]

    restart: "no"